# Generated by Django 5.1.2 on 2024-11-06 02:26

import Core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to=Core.models.Estacoe.gerar_rota)),
                ('icon', models.ImageField(upload_to=Core.models.Estacoe.gerar_rota_icon)),
                ('descricao_estacao', models.TextField(max_length=2000)),
                ('texto_funcionamento', models.TextField(max_length=1000)),
                ('responsabilidade', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Paleta_Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cor_principal', models.CharField(max_length=7)),
                ('cor_detalhes', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Imagens_equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=Core.models.Imagens_equipe.gerar_rota)),
                ('alt', models.CharField(max_length=100)),
                ('estacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.estacoe')),
            ],
        ),
        migrations.CreateModel(
            name='Imagens_Ideal_Para_Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to=Core.models.Imagens_Ideal_Para_Core.gerar_rota)),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.paleta_core')),
            ],
        ),
        migrations.CreateModel(
            name='Imagens_Beneficios_Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to=Core.models.Imagens_Beneficios_Core.gerar_rota)),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.paleta_core')),
            ],
        ),
        migrations.AddField(
            model_name='estacoe',
            name='cor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.paleta_core'),
        ),
        migrations.CreateModel(
            name='Texto_Beneficios_Estacoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficio', models.CharField(max_length=100)),
                ('estacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.estacoe')),
            ],
        ),
        migrations.CreateModel(
            name='Texto_Competencias_Estacoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(max_length=100)),
                ('estacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.estacoe')),
            ],
        ),
        migrations.CreateModel(
            name='Texto_Ideal_para_Estacoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ideal_para', models.CharField(max_length=100)),
                ('estacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.estacoe')),
            ],
        ),
        migrations.CreateModel(
            name='Texto_Servicos_Estacoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=100)),
                ('estacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.estacoe')),
            ],
        ),
    ]
