# Generated by Django 5.1.2 on 2024-11-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texto_competencias_estacoe',
            name='estacao',
        ),
        migrations.RemoveField(
            model_name='texto_ideal_para_estacoe',
            name='estacao',
        ),
        migrations.RemoveField(
            model_name='texto_servicos_estacoe',
            name='estacao',
        ),
        migrations.AddField(
            model_name='estacoe',
            name='Beneficios_1',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estacoe',
            name='Beneficios_2',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estacoe',
            name='Beneficios_3',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estacoe',
            name='Competencia_1',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estacoe',
            name='Competencia_2',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estacoe',
            name='Competencia_3',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estacoe',
            name='Ideal_para_1',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estacoe',
            name='Ideal_para_2',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estacoe',
            name='Ideal_para_3',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estacoe',
            name='Servico_1',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estacoe',
            name='Servico_2',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estacoe',
            name='Servico_3',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estacoe',
            name='descricao_estacao',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='estacoe',
            name='responsabilidade',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='Texto_Beneficios_Estacoe',
        ),
        migrations.DeleteModel(
            name='Texto_Competencias_Estacoe',
        ),
        migrations.DeleteModel(
            name='Texto_Ideal_para_Estacoe',
        ),
        migrations.DeleteModel(
            name='Texto_Servicos_Estacoe',
        ),
    ]
