# Generated by Django 5.1.2 on 2024-11-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_remove_texto_competencias_estacoe_estacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacoe',
            name='responsabilidade',
            field=models.TextField(max_length=1000),
        ),
    ]
