# Generated by Django 5.1.2 on 2024-11-21 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='name',
            new_name='nome_projeto',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='description',
        ),
        migrations.AddField(
            model_name='projeto',
            name='Progresso',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projeto',
            name='Proprietario',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='fase',
            field=models.CharField(choices=[('Andamento', 'Andamento'), ('Concluido', 'Concluido'), ('Descontinuado', 'Descontinuado')], default='Andamento', max_length=100),
        ),
        migrations.AddField(
            model_name='projeto',
            name='gestor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projetos_gestor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='numero_desafio',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projeto',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='integrantes',
            field=models.ManyToManyField(related_name='projetos_integrantes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('Em_andamento', 'Em_andamento'), ('Standy-by', 'Standy-by'), ('Concluido', 'Concluido'), ('Atrasado', 'Atrasado')], default='Em_andamento', max_length=255),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
