# Generated by Django 5.1.2 on 2024-11-23 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_estacoe_responsabilidade'),
        ('Dashboard', '0002_rename_name_projeto_nome_projeto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='estacao_projeto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Core.estacoe'),
            preserve_default=False,
        ),
    ]
