# Generated by Django 5.1.2 on 2024-11-23 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_projeto_estacao_projeto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='estacao_projeto',
            new_name='estacao',
        ),
    ]
