# Generated by Django 5.1.2 on 2024-11-23 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_estacoe_responsabilidade'),
        ('Dashboard', '0004_rename_estacao_projeto_projeto_estacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='estacao',
        ),
        migrations.AddField(
            model_name='projeto',
            name='estacao_projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.estacoe'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='id',
            field=models.BigIntegerField(default='<function generate_random_number at 0x000001AA96473E20>', primary_key=True, serialize=False, unique=True),
        ),
    ]
