# Generated by Django 5.1.2 on 2025-07-10 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_remove_projeto_estacao_projeto_estacao_projeto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='projeto',
            name='id',
            field=models.BigIntegerField(default='<function generate_random_number at 0x000001C8ABFCEC00>', primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Define a ordem de exibição do capítulo')),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='Dashboard.ebook')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ProgressoUsuarioEbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido', models.BooleanField(default=False)),
                ('data_conclusao', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.capitulo')),
            ],
            options={
                'unique_together': {('aluno', 'capitulo')},
            },
        ),
    ]
