# Generated by Django 5.1.2 on 2025-07-11 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_ebook_alter_projeto_id_capitulo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='conteudo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='id',
            field=models.BigIntegerField(default='<function generate_random_number at 0x7f7e7622b2e0>', primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='SubCapitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Vídeo'), ('texto', 'Texto'), ('exercicio', 'Exercício')], default='texto', max_length=20)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='subcapitulos/')),
                ('url_video', models.URLField(blank=True, null=True)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Define a ordem de exibição do subcapítulo')),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcapitulos', to='Dashboard.capitulo')),
            ],
            options={
                'verbose_name': 'Subcapítulo',
                'verbose_name_plural': 'Subcapítulos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ProgressoUsuarioSubCapitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido', models.BooleanField(default=False)),
                ('data_conclusao', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subcapitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.subcapitulo')),
            ],
            options={
                'verbose_name': 'Progresso de Subcapítulo',
                'verbose_name_plural': 'Progressos de Subcapítulos',
                'unique_together': {('aluno', 'subcapitulo')},
            },
        ),
    ]
