# Generated by Django 5.1.2 on 2025-07-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_alter_capitulo_conteudo_alter_projeto_id_subcapitulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='id',
            field=models.BigIntegerField(default='<function generate_random_number at 0x7f3ec6c972e0>', primary_key=True, serialize=False, unique=True),
        ),
    ]
