version: '3.8'

services:
  web:
    image: php:8.1-apache
    container_name: apache_php
    volumes:
      - ./www:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: ecommerceusados
      MYSQL_USER: user
      MYSQL_PASSWORD: "jovic"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "jovic"
    depends_on:
      - db

  node:
  node:
    image: node:16
    container_name: node_app
    working_dir: /app
    volumes:
      - ./backEnd:/app  # Ajuste para o caminho correto do código Node.js
    command: node conexao.js  # Rodar o código Node.js
    depends_on:
      - db  # Espera o banco de dados antes de iniciar o container


volumes:
  db_data:
